import { motion } from 'framer-motion';
import { HelpCircle, MessageCircle, Book, Mail } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

const supportOptions = [
  {
    icon: HelpCircle,
    title: 'Help Center',
    description: 'Browse our comprehensive help articles and tutorials',
    link: '/help',
    color: 'from-blue-600 to-blue-700'
  },
  {
    icon: Book,
    title: 'Documentation',
    description: 'Technical documentation and API reference guides',
    link: '/docs',
    color: 'from-green-600 to-green-700'
  },
  {
    icon: MessageCircle,
    title: 'Live Chat',
    description: 'Get instant help from our support team',
    link: '/chat',
    color: 'from-purple-600 to-purple-700'
  },
  {
    icon: Mail,
    title: 'Email Support',
    description: 'Send us a detailed message and we\'ll get back to you',
    link: 'mailto:support@plagiarismguard.ai',
    color: 'from-orange-600 to-orange-700'
  }
];

const faqs = [
  {
    question: 'How accurate is the plagiarism detection?',
    answer: 'Our AI-powered system achieves over 95% accuracy in detecting both exact matches and paraphrased content by using advanced semantic analysis and real-time web search.'
  },
  {
    question: 'What file formats are supported?',
    answer: 'We support .txt, .docx, and .pdf files up to 10MB in size. Our intelligent text extraction preserves formatting and structure.'
  },
  {
    question: 'Do you store my documents?',
    answer: 'No, we prioritize your privacy. Documents are processed in memory and automatically deleted after analysis. We never store your content unless you explicitly opt in.'
  },
  {
    question: 'Can I integrate this with my application?',
    answer: 'Yes! We provide a comprehensive REST API that allows you to integrate plagiarism detection directly into your applications. Check our API documentation for details.'
  },
  {
    question: 'How does AI content detection work?',
    answer: 'Our system analyzes text patterns, burstiness, and perplexity to identify content that may have been generated by AI tools like ChatGPT or other language models.'
  }
];

export default function Support() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 pt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-4">
            Support Center
          </h1>
          <p className="text-xl text-slate-600 dark:text-slate-400 max-w-3xl mx-auto">
            Get help with PlagiarismGuard AI and find answers to common questions
          </p>
        </motion.div>
        
        {/* Support Options */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {supportOptions.map((option, index) => (
            <motion.div
              key={option.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: index * 0.1 }}
            >
              <Card className="h-full hover:shadow-lg transition-all duration-300 hover:scale-105">
                <CardHeader className="text-center">
                  <div className={`w-12 h-12 bg-gradient-to-r ${option.color} rounded-lg flex items-center justify-center mx-auto mb-4`}>
                    <option.icon className="h-6 w-6 text-white" />
                  </div>
                  <CardTitle className="text-lg">{option.title}</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-slate-600 dark:text-slate-400 mb-4">
                    {option.description}
                  </p>
                  <Button 
                    asChild 
                    variant="outline" 
                    className="w-full"
                  >
                    <a href={option.link}>
                      Get Help
                    </a>
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
        
        {/* FAQ Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          <h2 className="text-3xl font-bold text-slate-900 dark:text-white text-center mb-8">
            Frequently Asked Questions
          </h2>
          
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.5 + index * 0.1 }}
              >
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg text-slate-900 dark:text-white">
                      {faq.question}
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-slate-600 dark:text-slate-400">
                      {faq.answer}
                    </p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </motion.div>
        
        {/* Contact CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.8 }}
          className="text-center mt-16"
        >
          <Card className="bg-gradient-to-r from-blue-600 to-purple-600 text-white">
            <CardContent className="py-8">
              <h3 className="text-2xl font-bold mb-4">
                Still Need Help?
              </h3>
              <p className="text-blue-100 mb-6">
                Our support team is here to help you get the most out of PlagiarismGuard AI
              </p>
              <div className="space-x-4">
                <Button variant="outline" className="bg-white text-blue-600 hover:bg-blue-50">
                  Contact Support
                </Button>
                <Button variant="outline" className="border-white text-white hover:bg-white/10">
                  Schedule a Demo
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
